spring.application.name=backlotBackend

# Server Config
server.port=8080

# Mongodb URI and DB
# Primary connection string
spring.mongodb.uri=${MONGODATA}

# JWT Config


# Spring Security
spring.security.user.name=user
spring.security.user.password=1234

